### ISSUE TITLE
Hard crash sending emails with SMTP disabled

### ISSUE THREAD

**Issue by soup-bowl** [soup-bowl/wp-simple-smtp#35]
**What WordPress, PHP and Simple SMTP versions are you using?**
WordPress 5.6.2, PHP 7.4.15, Simple SMTP 1.1.

**Describe the bug**
```
An error of type E_ERROR was caused in line 29 of the file <scrubbed>/wp-content/plugins/simple-smtp/src/mail/class-maildisable.php.
Error message: Uncaught Error: Class 'PHPMailerPHPMailerException' not found in <scrubbed>/wp-content/plugins/simple-smtp/src/mail/class-maildisable.php:29
Stack trace: 
#0 <scrubbed>/wp-includes/pluggable.php(498): wpsimplesmtpMailDisable->send() 
#1 <scrubbed>/wp-content/plugins/simple-smtp/src/mail/class-mailtest.php(110): wp_mail() 
#2 <scrubbed>/wp-includes/class-wp-hook.php(287): wpsimplesmtpMailtest::test_email_handler() 
#3 <scrubbed>/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters() 
#4 <scrubbed>/wp-includes/plugin.php(484): WP_Hook->do_action() 
#5 <scrubbed>/wp-admin/admin-post.php(70): do_action() #6 {main} thrown
```

**Steps to reproduce**
1. Install Simple SMTP on vanilla install.
2. Check 'disable emails'.
3. Send a test email.

**Comment by soup-bowl** [comment]
Weridly enough this doesn't happen on the Docker development environment, but happens on my production environment (yeah yeah I tried it on my website, shoot me). Investigating. Perhaps the container loads in PHPMailer differently.
